SmRidgebackFloorCoverageStatic1:
   signal_detector_loop_freq: 20

# RadialMotionStateMachine:
#     NavigateToRadialStart:
#         NavigationOrthogonalLine:
#             Navigate:
#                 start_position_x: 3
#                 start_position_y: 0
#     RotateDegress:
#         NavigationOrthogonalLine:
#             Navigate:
#                 initial_orientation_index: 0 # the initial index of the linear motion (factor of angle_increment_degrees)
#                 angle_increment_degree: 15    # the increment of angle between to linear motions
#                 linear_trajectories_count: 12  # the number of linear trajectories of the radial motion
#     NavigateToEndPoint:
#         NavigationOrthogonalLine:
#             Navigate:
#                 straight_motion_distance: 3.5