global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20
  publish_frequency: 5
  width: 250.0
  height: 120.0
  resolution: 0.3
  origin_x: -20.0
  origin_y: -20.0
  static_map: true
  rolling_window: false
  inflater_layer:
    inflation_radius: 0.6
