width: 4.0
height: 4.0
resolution: 0.025

plugins:
 - {name: obstacles, type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer"}

obstacles:
  publish_observations: false
