# Base profile
TrajectoryPlannerROS:
  acc_lim_x: 0.35
  acc_lim_y: 0.0
  acc_lim_theta: 0.8
  max_vel_x: 1.0
  min_vel_x: 0.15
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.3
  holonomic_robot: false

# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "rotate_recovery"
    type: "rotate_recovery/RotateRecovery"
  - name: "aggressive_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  reset_distance: 3.0
rotate_recovery:
  frequency: 20.0
  sim_granularity: 0.017
aggressive_reset: 
  reset_distance: 0.5
