joint_states:
  torso_lift_joint:  0.1
  head_pan_joint:  0.0
  head_tilt_joint:  0.018803999999999932
  shoulder_pan_joint:  -1.6056
  shoulder_lift_joint:  -0.4124472000000001
  upperarm_roll_joint:  0.0
  elbow_flex_joint:  -1.1799742
  forearm_roll_joint:   0.0
  wrist_flex_joint:   0.0
  wrist_roll_joint:   0.0
  r_gripper_finger_joint:  0.0
  l_gripper_finger_joint:  0.0
  bellows_joint:  0.0


