arm:
  #kinematics_solver: fetch_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver: fetch_arm/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 5
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
arm_with_torso:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: fetch_arm/IKFastKinematicsPlugin
  kinematics_solver_attempts: 5
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
